export const PROGRAMS_REQUEST = 'PROGRAMS_REQUEST';
export const PROGRAMS_SUCCESS = 'PROGRAMS_SUCCESS';
export const PROGRAMS_ERROR = 'PROGRAMS_ERROR';

export const SINGLE_PROGRAM_REQUEST = 'SINGLE_PROGRAM_REQUEST';
export const SINGLE_PROGRAM_SUCCESS = 'SINGLE_PROGRAM_SUCCESS';
export const SINGLE_PROGRAM_ERROR = 'SINGLE_PROGRAM_ERROR';

export const COURSE_REQUEST = 'COURSE_REQUEST';
export const COURSE_SUCCESS = 'COURSE_SUCCESS';
export const COURSE_ERROR = 'COURSE_ERROR';
