export const PROGRAMS_REQUEST = 'PROGRAMS_REQUEST';
export const PROGRAMS_SUCCESS = 'PROGRAMS_SUCCESS';
export const PROGRAMS_ERROR = 'PROGRAMS_ERROR';

export const SINGLE_PROGRAM_REQUEST = 'SINGLE_PROGRAM_REQUEST';
export const SINGLE_PROGRAM_SUCCESS = 'SINGLE_PROGRAM_SUCCESS';
export const SINGLE_PROGRAM_ERROR = 'SINGLE_PROGRAM_ERROR';

export const ADD_PROGRAM_REQUEST = 'ADD_PROGRAM_REQUEST';
export const ADD_PROGRAM_SUCCESS = 'ADD_PROGRAM_SUCCESS';
export const ADD_PROGRAM_ERROR = 'ADD_PROGRAM_ERROR';
