export const RESOURCES_REQUEST = 'RESOURCES_REQUEST';
export const RESOURCES_SUCCESS = 'RESOURCES_SUCCESS';
export const RESOURCES_ERROR = 'RESOURCES_ERROR';

export const ADD_RESOURCE_REQUEST = 'ADD_RESOURCE_REQUEST';
export const ADD_RESOURCE_SUCCESS = 'ADD_RESOURCE_SUCCESS';
export const ADD_RESOURCE_ERROR = 'ADD_RESOURCE_ERROR';
