export const REVIEWS_REQUEST = 'REVIEWS_REQUEST';
export const REVIEWS_SUCCESS = 'REVIEWS_SUCCESS';
export const REVIEWS_ERROR = 'REVIEWS_ERROR';

export const ADD_REVIEWS_REQUEST = 'ADD_REVIEWS_REQUEST';
export const ADD_REVIEWS_SUCCESS = 'ADD_REVIEWS_SUCCESS';
export const ADD_REVIEWS_ERROR = 'ADD_REVIEWS_ERROR';
